Repository mojohaus/mrm, pull requests merged in 2022-06, with the labels that each got.

#90 use gh action shared from ASF
  .github/workflows/maven.yml
Labels: build

#96 Extends example for maven-invoker-plugin
  mrm-maven-plugin/src/site/apt/examples/invoker-tests.apt.vm
Labels: documentation

#100 Refresh site descriptors, fix broken links
  mrm-api/src/site/site.xml
  mrm-maven-plugin/src/site/apt/index.apt
  mrm-maven-plugin/src/site/site.xml
  mrm-servlet/src/site/site.xml
  mrm-webapp/src/site/site.xml
  src/site/site.xml
Labels: documentation

#105 Fix unclosed opened stream
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/maven/ArtifactStoreFileSystem.java
  mrm-servlet/src/test/java/org/codehaus/mojo/mrm/impl/maven/ArtifactStoreFileSystemTest.java
Labels: bug

#112 Generate correct content of empty jars
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/Utils.java
  mrm-servlet/src/test/java/org/codehaus/mojo/mrm/impl/maven/MockArtifactStoreTest.java
  mrm-servlet/src/test/resources/empty-jar/mrm-empty-jar-1.0.pom
  mrm-servlet/src/test/resources/empty-plugin-jar/mrm-empty-plugin-jar-1.0.pom
Labels: bug

#113 Site improvement
  mrm-api/src/site/site.xml
  mrm-maven-plugin/src/site/site.xml
  mrm-servlet/src/site/site.xml
  mrm-webapp/src/site/site.xml
  src/site/site.xml
Labels: maintenance
