Repository mojohaus/mrm, pull requests merged in 2023-10, with the labels that each got.

#176 Remove support for listing directory as html page and cleanups
  mrm-api/src/main/java/org/codehaus/mojo/mrm/api/AbstractEntry.java
  mrm-api/src/main/java/org/codehaus/mojo/mrm/api/BaseFileEntry.java
  mrm-api/src/main/java/org/codehaus/mojo/mrm/api/BaseFileSystem.java
  mrm-api/src/main/java/org/codehaus/mojo/mrm/api/DefaultDirectoryEntry.java
  mrm-api/src/main/java/org/codehaus/mojo/mrm/api/Entry.java
  mrm-api/src/main/java/org/codehaus/mojo/mrm/api/FileSystem.java
  mrm-api/src/main/java/org/codehaus/mojo/mrm/api/ResolverUtils.java
  mrm-api/src/main/java/org/codehaus/mojo/mrm/api/maven/Artifact.java
  mrm-api/src/main/java/org/codehaus/mojo/mrm/api/maven/ArtifactStore.java
  mrm-api/src/main/java/org/codehaus/mojo/mrm/api/maven/BaseArtifactStore.java
  mrm-maven-plugin/src/main/java/org/codehaus/mojo/mrm/plugin/AbstractMRMMojo.java
  mrm-maven-plugin/src/main/java/org/codehaus/mojo/mrm/plugin/AbstractStartMojo.java
  mrm-maven-plugin/src/main/java/org/codehaus/mojo/mrm/plugin/ConsoleScanner.java
  mrm-maven-plugin/src/main/java/org/codehaus/mojo/mrm/plugin/FileSystemServer.java
  mrm-maven-plugin/src/main/java/org/codehaus/mojo/mrm/plugin/ProxyRepo.java
  mrm-maven-plugin/src/main/java/org/codehaus/mojo/mrm/plugin/RunMojo.java
  mrm-maven-plugin/src/main/java/org/codehaus/mojo/mrm/plugin/StartMojo.java
  mrm-maven-plugin/src/main/java/org/codehaus/mojo/mrm/plugin/StopMojo.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/GenerateOnErrorFileEntry.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/LinkFileEntry.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/RemoteFileEntry.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/Utils.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/digest/AutoDigestFileSystem.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/digest/MD5DigestFileEntry.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/digest/SHA1DigestFileEntry.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/maven/ArchetypeCatalogFileEntry.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/maven/ArtifactFileEntry.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/maven/CompositeArtifactStore.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/maven/DiskArtifactStore.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/maven/FileSystemArtifactStore.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/maven/MetadataFileEntry.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/maven/MockArtifactStore.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/servlet/FileSystemServlet.java
Labels: enhancement, breaking

#177 Dependencies cleanups
  mrm-api/pom.xml
  mrm-maven-plugin/pom.xml
  mrm-servlet/pom.xml
  pom.xml
Labels: maintenance

#180 Workaround for #179 - skip checksums for deployed metadata
  mrm-maven-plugin/src/it/hostedrepo/src/it/deploy-release/verify.groovy
  mrm-maven-plugin/src/it/hostedrepo/src/it/deploy-snapshot/verify.groovy
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/maven/ArtifactStoreFileSystem.java
Labels: bug

#182 Get rid of usage RepositoryMetadataManager
  mrm-api/src/main/java/org/codehaus/mojo/mrm/plugin/FactoryHelper.java
  mrm-maven-plugin/pom.xml
  mrm-maven-plugin/src/it/hostedrepo/src/it/plugins-metadata/invoker.properties
  mrm-maven-plugin/src/it/hostedrepo/src/it/plugins-metadata/pom.xml
  mrm-maven-plugin/src/it/hostedrepo/src/it/settings.xml
  mrm-maven-plugin/src/main/java/org/codehaus/mojo/mrm/maven/ProxyArtifactStore.java
  mrm-maven-plugin/src/main/java/org/codehaus/mojo/mrm/plugin/DefaultFactoryHelper.java
  mrm-maven-plugin/src/test/java/org/codehaus/mojo/mrm/maven/ProxyArtifactStoreTest.java
Labels: enhancement

#184 Require Maven 3.6.3+
  .github/workflows/maven.yml
  pom.xml
Labels: dependencies

#185 Support SNAPSHOT versions by localRepo
  mrm-api/src/main/java/org/codehaus/mojo/mrm/api/maven/Artifact.java
  mrm-maven-plugin/src/it/hostedrepo/pom.xml
  mrm-maven-plugin/src/it/hostedrepo/src/it/local-repo-snapshot-dep/pom.xml
  mrm-maven-plugin/src/it/hostedrepo/src/mrm-local-repo/org/group1/artifact1/1.0.0-SNAPSHOT/artifact1-1.0.0-SNAPSHOT.jar
  mrm-maven-plugin/src/it/hostedrepo/src/mrm-local-repo/org/group1/artifact1/1.0.0-SNAPSHOT/artifact1-1.0.0-SNAPSHOT.pom
  mrm-maven-plugin/src/it/hostedrepo/src/mrm-local-repo/org/group1/artifact2/1.0.0-SNAPSHOT/artifact1-1.0.0-20231008.222929-9999.jar
  mrm-maven-plugin/src/it/hostedrepo/src/mrm-local-repo/org/group1/artifact2/1.0.0-SNAPSHOT/artifact1-1.0.0-20231008.222929-9999.pom
  mrm-maven-plugin/src/it/hostedrepo/src/mrm-local-repo/org/group1/artifact2/1.0.0-SNAPSHOT/artifact2-1.0.0-20231008.222929-1.jar
  mrm-maven-plugin/src/it/hostedrepo/src/mrm-local-repo/org/group1/artifact2/1.0.0-SNAPSHOT/artifact2-1.0.0-20231008.222929-1.pom
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/maven/CompositeArtifactStore.java
  mrm-servlet/src/main/java/org/codehaus/mojo/mrm/impl/maven/DiskArtifactStore.java
  mrm-servlet/src/test/java/org/codehaus/mojo/mrm/impl/maven/CompositeArtifactStoreTest.java
  mrm-servlet/src/test/java/org/codehaus/mojo/mrm/impl/maven/DiskArtifactStoreTest.java
  mrm-servlet/src/test/resources/local-repo-unit/org/group1/artifact1/1.0.0/artifact1-1.0.0.pom
  mrm-servlet/src/test/resources/local-repo-unit/org/group2/artifact2/1.0.0-SNAPSHOT/artifact2-1.0.0-SNAPSHOT-build.pom
  mrm-servlet/src/test/resources/local-repo-unit/org/group2/artifact2/1.0.0-SNAPSHOT/artifact2-1.0.0-SNAPSHOT.jar
  mrm-servlet/src/test/resources/local-repo-unit/org/group2/artifact2/1.0.0-SNAPSHOT/artifact2-1.0.0-SNAPSHOT.pom
  mrm-servlet/src/test/resources/local-repo-unit/org/group2/artifact2/2.0.0-SNAPSHOT/artifact2-1.0.0-SNAPSHOT-build.pom
  mrm-servlet/src/test/resources/local-repo-unit/org/group2/artifact2/2.0.0-SNAPSHOT/artifact2-1.0.0-SNAPSHOT.pom
  mrm-servlet/src/test/resources/local-repo-unit/org/group2/artifact2/2.0.0-SNAPSHOT/artifact2-2.0.0-20231008.222929-1-build.pom
  mrm-servlet/src/test/resources/local-repo-unit/org/group2/artifact2/2.0.0-SNAPSHOT/artifact2-2.0.0-20231008.222929-1.jar
  mrm-servlet/src/test/resources/local-repo-unit/org/group2/artifact2/2.0.0-SNAPSHOT/artifact2-2.0.0-20231008.222929-1.pom
Labels: enhancement
